import bulbasaur from '../img/pokemons/bulbasaur.png';
import ivysaur from '../img/pokemons/ivysaur.png';
import venusaur from '../img/pokemons/venusaur.png';
import charmander from '../img/pokemons/charmander.png';
import charmeleon from '../img/pokemons/charmeleon.png';
import charizard from '../img/pokemons/charizard.png';
import squirtle from '../img/pokemons/squirtle.png';
import wartortle from '../img/pokemons/wartortle.png';
import blastoise from '../img/pokemons/blastoise.png';
import caterpie from '../img/pokemons/caterpie.png';
import metapod from '../img/pokemons/metapod.png';
import butterfree from '../img/pokemons/butterfree.png';
import weedle from '../img/pokemons/weedle.png';
import kakuna from '../img/pokemons/kakuna.png';
import beedrill from '../img/pokemons/beedrill.png';
import pidgey from '../img/pokemons/pidgey.png';
import pidgeotto from '../img/pokemons/pidgeotto.png';
import pidgeot from '../img/pokemons/pidgeot.png';
import rattata from '../img/pokemons/rattata.png';
import raticate from '../img/pokemons/raticate.png';

const pokemonsImgURL =  [
    {name: "bulbasaur", url: bulbasaur},
    {name: "ivysaur", url: ivysaur},
    {name: "venusaur", url: venusaur},
    {name: "charmander", url: charmander},
    {name: "charmeleon", url: charmeleon},
    {name: "charizard", url: charizard},
    {name: "squirtle", url: squirtle},
    {name: "wartortle", url: wartortle},
    {name: "blastoise", url: blastoise},
    {name: "caterpie", url: caterpie},
    {name: "metapod", url: metapod},
    {name: "butterfree", url: butterfree},
    {name: "weedle", url: weedle},
    {name: "kakuna", url: kakuna},
    {name: "beedrill", url: beedrill},
    {name: "pidgey", url: pidgey},
    {name: "pidgeotto", url: pidgeotto},
    {name: "pidgeot", url: pidgeot},
    {name: "rattata", url: rattata},
    {name: "raticate", url: raticate}
]
export default pokemonsImgURL;